### ISSUE TITLE
Freeze Sprite Frame Jump

### ISSUE THREAD

**Issue by J-Elijah** [FrancisClements/SuperSodaBomber#4]
Occurred while tap, tap and holding the _A_ or "Jump" Button.

**Comment by FrancisClements** [comment]
Did you both pressed space button and the A Button? Because I think that will be the problem.

**Comment by J-Elijah** [comment]
> Did you both pressed space button and the A Button? Because I think that will be the problem.

No, only the A button that is displayed on the screen
![2021-03-20 16-16-22_2](https://user-images.githubusercontent.com/69234724/111863916-2f35f900-8999-11eb-9c2f-62af961ca4eb.gif)

**Comment by FrancisClements** [comment]
I see. I think I know what the problem is.
I'll do it later lmao 😂

**Comment by FrancisClements** [comment]
Bug is now fixed.
Thank you and Happy Fiesta 🎉
